// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Backend.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrls")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<int?>("ParentReviewId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentReviewId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Backend.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCheckedOut")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Carts_UserId_NotCheckedOut")
                        .HasFilter("[IsCheckedOut] = 0");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Backend.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Nấu ăn và chế biến thực phẩm"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Làm mát và giữ lạnh"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Giặt giũ và vệ sinh"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Giải trí"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Chăm sóc cá nhân"
                        });
                });

            modelBuilder.Entity("Backend.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<int?>("Length")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentLinkId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QrCodeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ToDistrictId")
                        .HasColumnType("int");

                    b.Property<string>("ToDistrictName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ToProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("ToProvinceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ToWardCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ToWardName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VoucherCodeSnapshot")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VoucherId")
                        .HasColumnType("int");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Backend.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Backend.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ExpectedAmount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastEventAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<string>("PaymentLinkId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QrCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawPayload")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("RefId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentLinkId")
                        .IsUnique()
                        .HasFilter("[PaymentLinkId] IS NOT NULL");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduct"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRental")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdProduct");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            IdProduct = 1,
                            CategoryId = 1,
                            Condition = 0,
                            Description = "Nấu cơm nhanh, giữ ấm lâu, dễ vệ sinh.",
                            Image = "/images/giadung1.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Nồi cơm điện Cuckoo CR-0675F",
                            Price = 1590000m,
                            Quantity = 18,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 2,
                            CategoryId = 1,
                            Condition = 0,
                            Description = "Công nghệ Rapid Air giảm 90% dầu mỡ.",
                            Image = "/images/giadung2.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Nồi chiên không dầu Philips HD9200/90",
                            Price = 2290000m,
                            Quantity = 15,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 3,
                            CategoryId = 1,
                            Condition = 0,
                            Description = "Hâm, nấu, rã đông nhanh, núm xoay cơ học.",
                            Image = "/images/giadung3.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Lò vi sóng Sharp R-G226VN-BK",
                            Price = 1990000m,
                            Quantity = 14,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 4,
                            CategoryId = 1,
                            Condition = 0,
                            Description = "Công suất 700W, lưỡi dao thép không gỉ.",
                            Image = "/images/giadung4.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Máy xay sinh tố Philips HR2221/00",
                            Price = 1250000m,
                            Quantity = 12,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 5,
                            CategoryId = 1,
                            Condition = 0,
                            Description = "Pha espresso chất lượng, thiết kế nhỏ gọn.",
                            Image = "/images/giadung5.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Máy pha cà phê Delonghi EC685",
                            Price = 3990000m,
                            Quantity = 10,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 6,
                            CategoryId = 2,
                            Condition = 0,
                            Description = "Làm lạnh nhanh, khử mùi than hoạt tính.",
                            Image = "/images/lammat1.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Tủ lạnh Samsung Inverter 424 lít RT42CG6324B1SV",
                            Price = 14990000m,
                            Quantity = 7,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 7,
                            CategoryId = 2,
                            Condition = 0,
                            Description = "Bảo quản thực phẩm lâu dài, tiết kiệm điện.",
                            Image = "/images/lammat2.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Tủ đông Electrolux 200 lít EFZ2200H-H",
                            Price = 8990000m,
                            Quantity = 8,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 8,
                            CategoryId = 2,
                            Condition = 0,
                            Description = "Làm mát nhanh, lọc bụi, 3 chế độ gió.",
                            Image = "/images/lammat3.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Quạt điều hòa Midea AC120-19AR",
                            Price = 3290000m,
                            Quantity = 12,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 9,
                            CategoryId = 2,
                            Condition = 0,
                            Description = "Khử khuẩn, tiết kiệm điện vượt trội.",
                            Image = "/images/lammat4.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Máy điều hòa Daikin Inverter 1.5 HP FTKY35WMVMV",
                            Price = 11490000m,
                            Quantity = 9,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 10,
                            CategoryId = 2,
                            Condition = 0,
                            Description = "Tiện dụng, vận hành êm, thiết kế nhỏ gọn.",
                            Image = "/images/lammat5.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Quạt điện Asia F16001",
                            Price = 550000m,
                            Quantity = 20,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 11,
                            CategoryId = 3,
                            Condition = 0,
                            Description = "Công nghệ UltraMix hòa tan bột giặt.",
                            Image = "/images/giatgiu1.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Máy giặt Electrolux Inverter 10kg EWF1024BDWA",
                            Price = 8990000m,
                            Quantity = 10,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 12,
                            CategoryId = 3,
                            Condition = 0,
                            Description = "Rửa sạch, tiết kiệm nước, vận hành êm ái.",
                            Image = "/images/giatgiu2.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Máy rửa chén Bosch SMS25CI00E",
                            Price = 12990000m,
                            Quantity = 6,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 13,
                            CategoryId = 3,
                            Condition = 0,
                            Description = "Hút bụi tự động, lập bản đồ thông minh.",
                            Image = "/images/giatgiu3.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Robot hút bụi Xiaomi Mi Robot Vacuum",
                            Price = 4990000m,
                            Quantity = 15,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 14,
                            CategoryId = 3,
                            Condition = 0,
                            Description = "Loại bỏ bụi mịn, vi khuẩn và mùi hôi.",
                            Image = "/images/giatgiu4.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Máy lọc không khí Sharp FP-J40E-B",
                            Price = 3990000m,
                            Quantity = 8,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 15,
                            CategoryId = 3,
                            Condition = 0,
                            Description = "Sấy nhanh, tiết kiệm điện, bảo vệ vải.",
                            Image = "/images/giatgiu5.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Máy sấy quần áo Electrolux EDV705HQWA",
                            Price = 5990000m,
                            Quantity = 9,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 16,
                            CategoryId = 4,
                            Condition = 0,
                            Description = "Smart Tivi 4K sắc nét, hỗ trợ giọng nói.",
                            Image = "/images/giai_tri1.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Tivi Samsung Crystal UHD 55 inch BU8000",
                            Price = 12990000m,
                            Quantity = 12,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 17,
                            CategoryId = 4,
                            Condition = 0,
                            Description = "Âm thanh mạnh mẽ, pin 20 giờ.",
                            Image = "/images/giai_tri2.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Loa Bluetooth JBL Charge 5",
                            Price = 2590000m,
                            Quantity = 15,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 18,
                            CategoryId = 4,
                            Condition = 0,
                            Description = "Màn hình 4K sắc nét, hệ điều hành webOS, hỗ trợ điều khiển giọng nói.",
                            Image = "/images/giai_tri3.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Tivi LG 4K Smart TV 55 inch UQ7550",
                            Price = 11990000m,
                            Quantity = 10,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 19,
                            CategoryId = 4,
                            Condition = 0,
                            Description = "Chiếu phim Full HD, pin tích hợp.",
                            Image = "/images/giai_tri4.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Máy chiếu mini ViewSonic M1",
                            Price = 6990000m,
                            Quantity = 7,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 20,
                            CategoryId = 4,
                            Condition = 0,
                            Description = "Âm thanh vòm 3D sống động.",
                            Image = "/images/giai_tri5.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Loa Soundbar LG SN6Y",
                            Price = 3990000m,
                            Quantity = 9,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 21,
                            CategoryId = 5,
                            Condition = 0,
                            Description = "Cạo êm, bảo vệ da, pin 50 phút.",
                            Image = "/images/chamsoc1.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Máy cạo râu Philips Series 5000",
                            Price = 1599000m,
                            Quantity = 10,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 22,
                            CategoryId = 5,
                            Condition = 0,
                            Description = "Sấy nhanh, nhiệt độ ổn định, bảo vệ tóc.",
                            Image = "/images/chamsoc2.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Máy sấy tóc Panasonic EH-NA65",
                            Price = 1299000m,
                            Quantity = 12,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 23,
                            CategoryId = 5,
                            Condition = 0,
                            Description = "Thiết bị massage đa năng giúp thư giãn cơ bắp, giảm mệt mỏi và hỗ trợ lưu thông máu, phù hợp sử dụng tại nhà sau ngày làm việc căng thẳng.",
                            Image = "/images/chamsoc3.jpg",
                            IsDeleted = false,
                            IsRental = false,
                            Name = "Máy Massage Cầm Tay Beurer MG21",
                            Price = 1299000m,
                            Quantity = 15,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 24,
                            CategoryId = 5,
                            Condition = 0,
                            Description = "Làm sạch sâu, chống lão hóa, pin lâu dài.",
                            Image = "/images/chamsoc4.jpg",
                            IsDeleted = false,
                            IsRental = true,
                            Name = "Máy rửa mặt Foreo Luna Mini 3",
                            Price = 2499000m,
                            Quantity = 8,
                            Status = "ConHang"
                        },
                        new
                        {
                            IdProduct = 25,
                            CategoryId = 5,
                            Condition = 0,
                            Description = "Cạo nhanh, an toàn, dễ vệ sinh.",
                            Image = "/images/chamsoc5.jpg",
                            IsDeleted = false,
                            IsRental = true,
                            Name = "Máy cắt tóc Philips HC3505",
                            Price = 899000m,
                            Quantity = 10,
                            Status = "ConHang"
                        });
                });

            modelBuilder.Entity("Backend.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CleaningFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DamageFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepositPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepositRefund")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<decimal>("LateFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Length")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ToDistrictId")
                        .HasColumnType("int");

                    b.Property<string>("ToDistrictName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ToProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("ToProvinceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ToWardCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ToWardName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VoucherCodeSnapshot")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VoucherId")
                        .HasColumnType("int");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("Backend.Models.RentalItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DepositAtBooking")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LateFeePerUnitAtBooking")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerUnitAtBooking")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RentalId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RentalId");

                    b.ToTable("RentalItems");
                });

            modelBuilder.Entity("Backend.Models.RentalPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LateFeePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinUnits")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Unit")
                        .IsUnique();

                    b.ToTable("RentalPlans");
                });

            modelBuilder.Entity("Backend.Models.RentalPricingTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ThresholdDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "ThresholdDays")
                        .IsUnique();

                    b.ToTable("RentalPricingTiers");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TwoFactorAttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("TwoFactorCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime?>("TwoFactorCodeExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "https://localhost:44303/uploads/avatars/d580bd4e-3fce-4964-9e0c-53177f34082c.png",
                            CreatedAt = new DateTime(2025, 11, 11, 22, 27, 39, 707, DateTimeKind.Local).AddTicks(2879),
                            Email = "hoangphap1000@gmail.com",
                            FullName = "Lê Hoàng Pháp",
                            IsActive = true,
                            IsTwoFactorEnabled = false,
                            PasswordHash = "$2a$11$5WvpePUu2EIg8jo7MBWjvee3/uwro4V6QUIRSAju3HSEJVmvwcXJe",
                            PhoneNumber = "0564090866",
                            Role = "Admin",
                            TwoFactorAttemptCount = 0,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 16, 10, 32, 39, 924, DateTimeKind.Local).AddTicks(5745),
                            Email = "giang@example.com",
                            FullName = "Le Giang",
                            IsActive = true,
                            IsTwoFactorEnabled = false,
                            PasswordHash = "$2a$11$zB0cPctNLMkRJqNbC7qc7eF.VvtXVr1KmCuGUEoXC331zdp4Q9J.a",
                            PhoneNumber = "0773678161",
                            Role = "Admin",
                            TwoFactorAttemptCount = 0,
                            Username = "giang"
                        });
                });

            modelBuilder.Entity("Backend.Models.Vouncher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ApplyToShipping")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentUsageCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<int>("MaxUsageCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaximumDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumOrderValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ShippingDiscountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Vounchers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplyToShipping = false,
                            Code = "GIAM500K",
                            CurrentUsageCount = 0,
                            DiscountValue = 500000m,
                            ExpirationDate = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsValid = true,
                            MaxUsageCount = 100,
                            MinimumOrderValue = 5000000m,
                            Type = "fixed"
                        },
                        new
                        {
                            Id = 2,
                            ApplyToShipping = false,
                            Code = "GIAM1M",
                            CurrentUsageCount = 0,
                            DiscountValue = 1000000m,
                            ExpirationDate = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsValid = true,
                            MaxUsageCount = 50,
                            MinimumOrderValue = 10000000m,
                            Type = "fixed"
                        },
                        new
                        {
                            Id = 3,
                            ApplyToShipping = false,
                            Code = "GIAM10",
                            CurrentUsageCount = 0,
                            DiscountPercent = 10m,
                            ExpirationDate = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsValid = true,
                            MaxUsageCount = 200,
                            MaximumDiscount = 500000m,
                            MinimumOrderValue = 2000000m,
                            Type = "percent"
                        },
                        new
                        {
                            Id = 4,
                            ApplyToShipping = false,
                            Code = "GIAM20",
                            CurrentUsageCount = 0,
                            DiscountPercent = 20m,
                            ExpirationDate = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsValid = true,
                            MaxUsageCount = 100,
                            MaximumDiscount = 1000000m,
                            MinimumOrderValue = 5000000m,
                            Type = "percent"
                        },
                        new
                        {
                            Id = 5,
                            ApplyToShipping = false,
                            Code = "GIAM30",
                            CurrentUsageCount = 0,
                            DiscountPercent = 30m,
                            ExpirationDate = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsValid = true,
                            MaxUsageCount = 30,
                            MaximumDiscount = 2000000m,
                            MinimumOrderValue = 10000000m,
                            Type = "percent"
                        },
                        new
                        {
                            Id = 6,
                            ApplyToShipping = true,
                            Code = "FREESHIP",
                            CurrentUsageCount = 0,
                            ExpirationDate = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsValid = true,
                            MaxUsageCount = 500,
                            MinimumOrderValue = 1000000m,
                            Type = "shipping"
                        },
                        new
                        {
                            Id = 7,
                            ApplyToShipping = true,
                            Code = "SHIP50",
                            CurrentUsageCount = 0,
                            ExpirationDate = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsValid = true,
                            MaxUsageCount = 300,
                            MinimumOrderValue = 500000m,
                            ShippingDiscountPercent = 50m,
                            Type = "shipping"
                        },
                        new
                        {
                            Id = 8,
                            ApplyToShipping = false,
                            Code = "COMBO200K",
                            CurrentUsageCount = 0,
                            DiscountValue = 200000m,
                            ExpirationDate = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsValid = true,
                            MaxUsageCount = 150,
                            MinimumOrderValue = 3000000m,
                            Type = "fixed"
                        },
                        new
                        {
                            Id = 13,
                            ApplyToShipping = true,
                            Code = "COMBOSHIP",
                            CurrentUsageCount = 0,
                            ExpirationDate = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsValid = true,
                            MaxUsageCount = 150,
                            MinimumOrderValue = 3000000m,
                            Type = "shipping"
                        },
                        new
                        {
                            Id = 9,
                            ApplyToShipping = false,
                            Code = "THUE100K",
                            CurrentUsageCount = 0,
                            DiscountValue = 100000m,
                            ExpirationDate = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsValid = true,
                            MaxUsageCount = 200,
                            MinimumOrderValue = 100000m,
                            Type = "fixed"
                        },
                        new
                        {
                            Id = 10,
                            ApplyToShipping = false,
                            Code = "THUE15",
                            CurrentUsageCount = 0,
                            DiscountPercent = 15m,
                            ExpirationDate = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsValid = true,
                            MaxUsageCount = 100,
                            MaximumDiscount = 300000m,
                            MinimumOrderValue = 2000000m,
                            Type = "percent"
                        },
                        new
                        {
                            Id = 11,
                            ApplyToShipping = false,
                            Code = "EXPIRED",
                            CurrentUsageCount = 0,
                            DiscountValue = 500000m,
                            ExpirationDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsValid = true,
                            MaxUsageCount = 10,
                            MinimumOrderValue = 1000000m,
                            Type = "fixed"
                        },
                        new
                        {
                            Id = 12,
                            ApplyToShipping = false,
                            Code = "SOLDOUT",
                            CurrentUsageCount = 5,
                            DiscountPercent = 25m,
                            ExpirationDate = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsValid = true,
                            MaxUsageCount = 5,
                            MaximumDiscount = 1000000m,
                            MinimumOrderValue = 3000000m,
                            Type = "percent"
                        });
                });

            modelBuilder.Entity("Backend.Models.Backend.Models.Review", b =>
                {
                    b.HasOne("Backend.Models.Backend.Models.Review", "ParentReview")
                        .WithMany("Replies")
                        .HasForeignKey("ParentReviewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentReview");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Cart", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.CartItem", b =>
                {
                    b.HasOne("Backend.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.Order", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Vouncher", "Voucher")
                        .WithMany("Orders")
                        .HasForeignKey("VoucherId");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Backend.Models.OrderItem", b =>
                {
                    b.HasOne("Backend.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.HasOne("Backend.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Backend.Models.Rental", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Vouncher", "Voucher")
                        .WithMany("Rentals")
                        .HasForeignKey("VoucherId");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Backend.Models.RentalItem", b =>
                {
                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Rental", "Rental")
                        .WithMany("Items")
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("Backend.Models.Backend.Models.Review", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Backend.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Backend.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Backend.Models.Rental", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Backend.Models.Vouncher", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
